version: 2
jobs:
  build:

    working_directory: ~/qa-example-web-barter

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run:
          name: build
          command: gradle clean build

      - run:
          name: test
          command: gradle clean test aggregate
