version: 2
jobs:
  build:

    working_directory: ~/qa-example-web-barter

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
            key: circleci-qa-example-web-barter-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-qa-example-web-barter-{{ checksum "build.gradle" }}

      - run:
          name: build
          command: gradle clean build

      - run:
          name: test
          command: gradle clean test aggregate

      - store_test_results:
          path: target
